### ISSUE TITLE
Add Time for web version

### ISSUE THREAD

**Issue by Medhansh-shah** [eduCode-Inc/EOM_Calculator#1]

**Comment by tanay-desai** [comment]
Ok. Will complete as soon as possible.

**Comment by Medhansh-shah** [comment]
Sorry that was a typing error. I wanted to write Time only.

**Comment by Medhansh-shah** [comment]
Now it's changed (The title)

**Comment by Medhansh-shah** [comment]
Close this issue once you finish Time

**Comment by Medhansh-shah** [comment]
I have the reviewed the code. It's working fine. Closing issue with this comment.

**Comment by tanay-desai** [comment]
Ohk thank you
